export type LineId = 'MRT-3' | 'LRT-1' | 'LRT-2';

export interface NearbyPlace {
  name: string;
  type: 'food' | 'shop' | 'landmark' | 'mall' | 'hospital' | 'school';
  distance: string;
}

export interface Station {
  id: string;
  name: string;
  line: LineId;
  lineIndex: number;
  isTransfer: boolean;
  transferTo?: LineId[];
  firstTrain: string;
  lastTrain: string;
  platforms: number;
  exits: string[];
  nearbyStreets: string[];
  nearbyPlaces: NearbyPlace[];
  latitude: number;
  longitude: number;
  status: 'Normal' | 'Delayed' | 'Closed' | 'Maintenance';
}

export const LINE_COLORS: Record<LineId, string> = {
  'MRT-3': '#4499FF', // Neon Blue
  'LRT-1': '#FFE600', // Neon Yellow
  'LRT-2': '#BB44FF', // Neon Violet
};

export const LINE_NAMES: Record<LineId, string> = {
  'MRT-3': 'MRT Line 3',
  'LRT-1': 'LRT Line 1',
  'LRT-2': 'LRT Line 2',
};

export const MRT3_STATIONS: Station[] = [
  {
    id: 'mrt3-north-avenue',
    name: 'North Avenue',
    line: 'MRT-3',
    lineIndex: 0,
    isTransfer: false,
    firstTrain: '5:30 AM',
    lastTrain: '10:30 PM',
    platforms: 2,
    exits: ['Exit 1 - North Avenue', 'Exit 2 - Trinoma Mall'],
    nearbyStreets: ['North Avenue', 'EDSA'],
    nearbyPlaces: [
      { name: 'Trinoma Mall', type: 'mall', distance: '50m' },
      { name: 'SM North EDSA', type: 'mall', distance: '300m' },
      { name: 'Jollibee Trinoma', type: 'food', distance: '100m' },
    ],
    latitude: 14.6522,
    longitude: 121.0320,
    status: 'Normal',
  },
  {
    id: 'mrt3-quezon-avenue',
    name: 'Quezon Avenue',
    line: 'MRT-3',
    lineIndex: 1,
    isTransfer: false,
    firstTrain: '5:30 AM',
    lastTrain: '10:30 PM',
    platforms: 2,
    exits: ['Exit 1 - Quezon Avenue', 'Exit 2 - EDSA'],
    nearbyStreets: ['Quezon Avenue', 'EDSA'],
    nearbyPlaces: [
      { name: 'Eton Centris', type: 'mall', distance: '100m' },
      { name: 'Phoenix Gas Station', type: 'landmark', distance: '200m' },
    ],
    latitude: 14.6427,
    longitude: 121.0386,
    status: 'Normal',
  },
  {
    id: 'mrt3-gma-kamuning',
    name: 'GMA Kamuning',
    line: 'MRT-3',
    lineIndex: 2,
    isTransfer: false,
    firstTrain: '5:30 AM',
    lastTrain: '10:30 PM',
    platforms: 2,
    exits: ['Exit 1 - Kamuning Road', 'Exit 2 - EDSA'],
    nearbyStreets: ['Kamuning Road', 'EDSA'],
    nearbyPlaces: [
      { name: 'GMA Network Center', type: 'landmark', distance: '200m' },
      { name: 'KFC Kamuning', type: 'food', distance: '150m' },
    ],
    latitude: 14.6353,
    longitude: 121.0434,
    status: 'Normal',
  },
  {
    id: 'mrt3-araneta-cubao',
    name: 'Araneta Center-Cubao',
    line: 'MRT-3',
    lineIndex: 3,
    isTransfer: true,
    transferTo: ['LRT-2'],
    firstTrain: '5:30 AM',
    lastTrain: '10:30 PM',
    platforms: 2,
    exits: ['Exit 1 - Gateway Mall', 'Exit 2 - Farmers Plaza', 'Exit 3 - LRT-2 Connection'],
    nearbyStreets: ['EDSA', 'Aurora Boulevard', 'General Romulo Avenue'],
    nearbyPlaces: [
      { name: 'Gateway Mall', type: 'mall', distance: '50m' },
      { name: 'Farmers Plaza', type: 'mall', distance: '100m' },
      { name: 'Ali Mall', type: 'mall', distance: '200m' },
      { name: 'Smart Araneta Coliseum', type: 'landmark', distance: '150m' },
    ],
    latitude: 14.6225,
    longitude: 121.0530,
    status: 'Normal',
  },
  {
    id: 'mrt3-santolan-annapolis',
    name: 'Santolan-Annapolis',
    line: 'MRT-3',
    lineIndex: 4,
    isTransfer: false,
    firstTrain: '5:30 AM',
    lastTrain: '10:30 PM',
    platforms: 2,
    exits: ['Exit 1 - Annapolis Street', 'Exit 2 - EDSA'],
    nearbyStreets: ['EDSA', 'Annapolis Street'],
    nearbyPlaces: [
      { name: 'Greenhills Shopping Center', type: 'mall', distance: '400m' },
      { name: 'Viridian Condo', type: 'landmark', distance: '200m' },
    ],
    latitude: 14.6073,
    longitude: 121.0569,
    status: 'Normal',
  },
  {
    id: 'mrt3-ortigas',
    name: 'Ortigas',
    line: 'MRT-3',
    lineIndex: 5,
    isTransfer: false,
    firstTrain: '5:30 AM',
    lastTrain: '10:30 PM',
    platforms: 2,
    exits: ['Exit 1 - Ortigas Avenue', 'Exit 2 - EDSA', 'Exit 3 - Robinsons Galleria'],
    nearbyStreets: ['EDSA', 'Ortigas Avenue'],
    nearbyPlaces: [
      { name: 'Robinsons Galleria', type: 'mall', distance: '50m' },
      { name: 'SM Megamall', type: 'mall', distance: '300m' },
      { name: 'The Podium', type: 'mall', distance: '500m' },
    ],
    latitude: 14.5879,
    longitude: 121.0569,
    status: 'Normal',
  },
  {
    id: 'mrt3-shaw-boulevard',
    name: 'Shaw Boulevard',
    line: 'MRT-3',
    lineIndex: 6,
    isTransfer: false,
    firstTrain: '5:30 AM',
    lastTrain: '10:30 PM',
    platforms: 2,
    exits: ['Exit 1 - Shaw Boulevard', 'Exit 2 - EDSA'],
    nearbyStreets: ['EDSA', 'Shaw Boulevard'],
    nearbyPlaces: [
      { name: 'Shangri-La Plaza', type: 'mall', distance: '200m' },
      { name: 'Starmall EDSA', type: 'mall', distance: '300m' },
    ],
    latitude: 14.5812,
    longitude: 121.0546,
    status: 'Normal',
  },
  {
    id: 'mrt3-boni',
    name: 'Boni',
    line: 'MRT-3',
    lineIndex: 7,
    isTransfer: false,
    firstTrain: '5:30 AM',
    lastTrain: '10:30 PM',
    platforms: 2,
    exits: ['Exit 1 - Pioneer Street', 'Exit 2 - EDSA'],
    nearbyStreets: ['EDSA', 'Pioneer Street'],
    nearbyPlaces: [
      { name: 'Pioneer Centre', type: 'mall', distance: '200m' },
      { name: 'Jollibee Pioneer', type: 'food', distance: '150m' },
    ],
    latitude: 14.5735,
    longitude: 121.0485,
    status: 'Normal',
  },
  {
    id: 'mrt3-guadalupe',
    name: 'Guadalupe',
    line: 'MRT-3',
    lineIndex: 8,
    isTransfer: false,
    firstTrain: '5:30 AM',
    lastTrain: '10:30 PM',
    platforms: 2,
    exits: ['Exit 1 - JP Rizal Street', 'Exit 2 - EDSA'],
    nearbyStreets: ['EDSA', 'JP Rizal Street'],
    nearbyPlaces: [
      { name: 'Guadalupe Market', type: 'food', distance: '100m' },
      { name: 'Guadalupe Bridge', type: 'landmark', distance: '200m' },
    ],
    latitude: 14.5667,
    longitude: 121.0456,
    status: 'Normal',
  },
  {
    id: 'mrt3-buendia',
    name: 'Buendia',
    line: 'MRT-3',
    lineIndex: 9,
    isTransfer: false,
    firstTrain: '5:30 AM',
    lastTrain: '10:30 PM',
    platforms: 2,
    exits: ['Exit 1 - Sen. Gil Puyat Avenue', 'Exit 2 - EDSA'],
    nearbyStreets: ['EDSA', 'Sen. Gil Puyat Avenue'],
    nearbyPlaces: [
      { name: 'Buendia Food Hub', type: 'food', distance: '100m' },
      { name: 'The Columns Ayala', type: 'landmark', distance: '300m' },
    ],
    latitude: 14.5545,
    longitude: 121.0345,
    status: 'Normal',
  },
  {
    id: 'mrt3-ayala',
    name: 'Ayala',
    line: 'MRT-3',
    lineIndex: 10,
    isTransfer: false,
    firstTrain: '5:30 AM',
    lastTrain: '10:30 PM',
    platforms: 2,
    exits: ['Exit 1 - Ayala Avenue', 'Exit 2 - Glorietta', 'Exit 3 - Greenbelt'],
    nearbyStreets: ['EDSA', 'Ayala Avenue', 'Makati Avenue'],
    nearbyPlaces: [
      { name: 'Glorietta', type: 'mall', distance: '100m' },
      { name: 'Greenbelt', type: 'mall', distance: '200m' },
      { name: 'Ayala Triangle Gardens', type: 'landmark', distance: '300m' },
      { name: 'SM Makati', type: 'mall', distance: '150m' },
    ],
    latitude: 14.5492,
    longitude: 121.0288,
    status: 'Normal',
  },
  {
    id: 'mrt3-magallanes',
    name: 'Magallanes',
    line: 'MRT-3',
    lineIndex: 11,
    isTransfer: false,
    firstTrain: '5:30 AM',
    lastTrain: '10:30 PM',
    platforms: 2,
    exits: ['Exit 1 - Magallanes Village', 'Exit 2 - EDSA'],
    nearbyStreets: ['EDSA', 'Magallanes Drive'],
    nearbyPlaces: [
      { name: 'Alphaland Southgate', type: 'mall', distance: '300m' },
    ],
    latitude: 14.5420,
    longitude: 121.0196,
    status: 'Normal',
  },
  {
    id: 'mrt3-taft-avenue',
    name: 'Taft Avenue',
    line: 'MRT-3',
    lineIndex: 12,
    isTransfer: true,
    transferTo: ['LRT-1'],
    firstTrain: '5:30 AM',
    lastTrain: '10:30 PM',
    platforms: 2,
    exits: ['Exit 1 - Taft Avenue', 'Exit 2 - EDSA', 'Exit 3 - LRT-1 Connection'],
    nearbyStreets: ['EDSA', 'Taft Avenue'],
    nearbyPlaces: [
      { name: 'DLSU Manila', type: 'school', distance: '500m' },
      { name: 'Pasay Rotonda', type: 'landmark', distance: '200m' },
    ],
    latitude: 14.5374,
    longitude: 121.0008,
    status: 'Normal',
  },
];

export const LRT1_STATIONS: Station[] = [
  {
    id: 'lrt1-fpj',
    name: 'Fernando Poe Jr. (FPJ)',
    line: 'LRT-1',
    lineIndex: 0,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Fernando Poe Jr. Avenue', 'Exit 2 - Rizal Avenue Extension'],
    nearbyStreets: ['Fernando Poe Jr. Avenue', 'Rizal Avenue Extension'],
    nearbyPlaces: [
      { name: 'Fisher Mall', type: 'mall', distance: '200m' },
      { name: 'SM Fairview', type: 'mall', distance: '2km' },
    ],
    latitude: 14.6575,
    longitude: 120.9837,
    status: 'Normal',
  },
  {
    id: 'lrt1-balintawak',
    name: 'Balintawak',
    line: 'LRT-1',
    lineIndex: 1,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - EDSA', 'Exit 2 - Cloverleaf Market'],
    nearbyStreets: ['EDSA', 'Rizal Avenue Extension'],
    nearbyPlaces: [
      { name: 'Cloverleaf Market', type: 'food', distance: '100m' },
    ],
    latitude: 14.6574,
    longitude: 120.9937,
    status: 'Normal',
  },
  {
    id: 'lrt1-monumento',
    name: 'Monumento',
    line: 'LRT-1',
    lineIndex: 2,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Rizal Avenue', 'Exit 2 - McArthur Highway'],
    nearbyStreets: ['Rizal Avenue', 'McArthur Highway'],
    nearbyPlaces: [
      { name: 'Bonifacio Monument', type: 'landmark', distance: '50m' },
      { name: 'Victory Mall', type: 'mall', distance: '200m' },
    ],
    latitude: 14.6545,
    longitude: 120.9838,
    status: 'Normal',
  },
  {
    id: 'lrt1-5th-avenue',
    name: '5th Avenue',
    line: 'LRT-1',
    lineIndex: 3,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - 5th Avenue'],
    nearbyStreets: ['5th Avenue', 'Rizal Avenue'],
    nearbyPlaces: [
      { name: 'Grace Park Market', type: 'food', distance: '300m' },
    ],
    latitude: 14.6444,
    longitude: 120.9835,
    status: 'Normal',
  },
  {
    id: 'lrt1-r-papa',
    name: 'R. Papa',
    line: 'LRT-1',
    lineIndex: 4,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - R. Papa Street'],
    nearbyStreets: ['R. Papa Street', 'Rizal Avenue'],
    nearbyPlaces: [],
    latitude: 14.6358,
    longitude: 120.9832,
    status: 'Normal',
  },
  {
    id: 'lrt1-abad-santos',
    name: 'Abad Santos',
    line: 'LRT-1',
    lineIndex: 5,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Abad Santos Avenue'],
    nearbyStreets: ['Abad Santos Avenue', 'Rizal Avenue'],
    nearbyPlaces: [],
    latitude: 14.6303,
    longitude: 120.9815,
    status: 'Normal',
  },
  {
    id: 'lrt1-blumentritt',
    name: 'Blumentritt',
    line: 'LRT-1',
    lineIndex: 6,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Blumentritt Road'],
    nearbyStreets: ['Blumentritt Road', 'Rizal Avenue'],
    nearbyPlaces: [
      { name: 'Blumentritt Market', type: 'food', distance: '100m' },
    ],
    latitude: 14.6227,
    longitude: 120.9828,
    status: 'Normal',
  },
  {
    id: 'lrt1-tayuman',
    name: 'Tayuman',
    line: 'LRT-1',
    lineIndex: 7,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Tayuman Street'],
    nearbyStreets: ['Tayuman Street', 'Rizal Avenue'],
    nearbyPlaces: [],
    latitude: 14.6165,
    longitude: 120.9828,
    status: 'Normal',
  },
  {
    id: 'lrt1-bambang',
    name: 'Bambang',
    line: 'LRT-1',
    lineIndex: 8,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Bambang Street'],
    nearbyStreets: ['Bambang Street', 'Rizal Avenue'],
    nearbyPlaces: [],
    latitude: 14.6110,
    longitude: 120.9824,
    status: 'Normal',
  },
  {
    id: 'lrt1-doroteo-jose',
    name: 'Doroteo Jose',
    line: 'LRT-1',
    lineIndex: 9,
    isTransfer: true,
    transferTo: ['LRT-2'],
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Doroteo Jose Street', 'Exit 2 - Recto Avenue', 'Exit 3 - LRT-2 Connection'],
    nearbyStreets: ['Doroteo Jose Street', 'Recto Avenue', 'Rizal Avenue'],
    nearbyPlaces: [
      { name: 'Isetann Recto', type: 'mall', distance: '200m' },
      { name: 'Raon Electronics Hub', type: 'shop', distance: '300m' },
    ],
    latitude: 14.6055,
    longitude: 120.9819,
    status: 'Normal',
  },
  {
    id: 'lrt1-carriedo',
    name: 'Carriedo',
    line: 'LRT-1',
    lineIndex: 10,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Carriedo Street'],
    nearbyStreets: ['Carriedo Street', 'Rizal Avenue'],
    nearbyPlaces: [
      { name: 'Quiapo Church', type: 'landmark', distance: '200m' },
      { name: 'Quiapo Market', type: 'shop', distance: '100m' },
    ],
    latitude: 14.5990,
    longitude: 120.9810,
    status: 'Normal',
  },
  {
    id: 'lrt1-central-terminal',
    name: 'Central Terminal',
    line: 'LRT-1',
    lineIndex: 11,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Arroceros Street'],
    nearbyStreets: ['Arroceros Street', 'Taft Avenue'],
    nearbyPlaces: [
      { name: 'Manila City Hall', type: 'landmark', distance: '300m' },
    ],
    latitude: 14.5925,
    longitude: 120.9816,
    status: 'Normal',
  },
  {
    id: 'lrt1-un-avenue',
    name: 'United Nations',
    line: 'LRT-1',
    lineIndex: 12,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - UN Avenue'],
    nearbyStreets: ['UN Avenue', 'Taft Avenue'],
    nearbyPlaces: [
      { name: 'Manila Doctors Hospital', type: 'hospital', distance: '200m' },
      { name: 'Robinsons Place Manila', type: 'mall', distance: '300m' },
    ],
    latitude: 14.5822,
    longitude: 120.9846,
    status: 'Normal',
  },
  {
    id: 'lrt1-pedro-gil',
    name: 'Pedro Gil',
    line: 'LRT-1',
    lineIndex: 13,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Pedro Gil Street'],
    nearbyStreets: ['Pedro Gil Street', 'Taft Avenue'],
    nearbyPlaces: [
      { name: 'Philippine General Hospital', type: 'hospital', distance: '300m' },
    ],
    latitude: 14.5762,
    longitude: 120.9879,
    status: 'Normal',
  },
  {
    id: 'lrt1-quirino',
    name: 'Quirino',
    line: 'LRT-1',
    lineIndex: 14,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Quirino Avenue'],
    nearbyStreets: ['Quirino Avenue', 'Taft Avenue'],
    nearbyPlaces: [
      { name: 'Harrison Plaza', type: 'mall', distance: '400m' },
    ],
    latitude: 14.5703,
    longitude: 120.9914,
    status: 'Normal',
  },
  {
    id: 'lrt1-vito-cruz',
    name: 'Vito Cruz',
    line: 'LRT-1',
    lineIndex: 15,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Vito Cruz Street'],
    nearbyStreets: ['Vito Cruz Street', 'Taft Avenue'],
    nearbyPlaces: [
      { name: 'De La Salle University', type: 'school', distance: '100m' },
    ],
    latitude: 14.5636,
    longitude: 120.9946,
    status: 'Normal',
  },
  {
    id: 'lrt1-gil-puyat',
    name: 'Gil Puyat',
    line: 'LRT-1',
    lineIndex: 16,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Gil Puyat Avenue'],
    nearbyStreets: ['Sen. Gil Puyat Avenue', 'Taft Avenue'],
    nearbyPlaces: [
      { name: 'World Trade Center', type: 'landmark', distance: '500m' },
    ],
    latitude: 14.5544,
    longitude: 120.9966,
    status: 'Normal',
  },
  {
    id: 'lrt1-libertad',
    name: 'Libertad',
    line: 'LRT-1',
    lineIndex: 17,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Libertad Street'],
    nearbyStreets: ['Libertad Street', 'Taft Avenue'],
    nearbyPlaces: [
      { name: 'Pasay City Market', type: 'food', distance: '200m' },
    ],
    latitude: 14.5477,
    longitude: 120.9985,
    status: 'Normal',
  },
  {
    id: 'lrt1-edsa',
    name: 'EDSA',
    line: 'LRT-1',
    lineIndex: 18,
    isTransfer: true,
    transferTo: ['MRT-3'],
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - EDSA', 'Exit 2 - Taft Avenue', 'Exit 3 - MRT-3 Connection'],
    nearbyStreets: ['EDSA', 'Taft Avenue'],
    nearbyPlaces: [
      { name: 'SM Mall of Asia', type: 'mall', distance: '2km' },
    ],
    latitude: 14.5392,
    longitude: 121.0005,
    status: 'Normal',
  },
  {
    id: 'lrt1-baclaran',
    name: 'Baclaran',
    line: 'LRT-1',
    lineIndex: 19,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Redemptorist Road', 'Exit 2 - Roxas Boulevard'],
    nearbyStreets: ['Redemptorist Road', 'Roxas Boulevard'],
    nearbyPlaces: [
      { name: 'Baclaran Church', type: 'landmark', distance: '100m' },
      { name: 'Baclaran Market', type: 'shop', distance: '50m' },
    ],
    latitude: 14.5340,
    longitude: 120.9982,
    status: 'Normal',
  },
  // ── Cavite Extension Stations (2026) ─────────────────────────────────────
  {
    id: 'lrt1-redemptorist-aseana',
    name: 'Redemptorist-Aseana',
    line: 'LRT-1',
    lineIndex: 20,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Redemptorist Road', 'Exit 2 - Aseana Avenue'],
    nearbyStreets: ['Redemptorist Road', 'Aseana Avenue', 'Roxas Boulevard'],
    nearbyPlaces: [
      { name: 'Aseana City Business Park', type: 'landmark', distance: '100m' },
      { name: 'Aseana One', type: 'shop', distance: '200m' },
    ],
    latitude: 14.5218,
    longitude: 121.0003,
    status: 'Normal',
  },
  {
    id: 'lrt1-mia-road',
    name: 'MIA Road',
    line: 'LRT-1',
    lineIndex: 21,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - MIA Road', 'Exit 2 - Andrews Avenue'],
    nearbyStreets: ['MIA Road', 'Andrews Avenue'],
    nearbyPlaces: [
      { name: 'NAIA Terminal Area', type: 'landmark', distance: '500m' },
    ],
    latitude: 14.5131,
    longitude: 120.9985,
    status: 'Normal',
  },
  {
    id: 'lrt1-pitx',
    name: 'PITX',
    line: 'LRT-1',
    lineIndex: 22,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - PITX Terminal', 'Exit 2 - Entertainment City Road'],
    nearbyStreets: ['PITX Road', 'Entertainment City Road'],
    nearbyPlaces: [
      { name: 'Parañaque Integrated Terminal Exchange', type: 'landmark', distance: '50m' },
      { name: 'Okada Manila', type: 'landmark', distance: '500m' },
    ],
    latitude: 14.4985,
    longitude: 120.9925,
    status: 'Normal',
  },
  {
    id: 'lrt1-ninoy-aquino-ave',
    name: 'Ninoy Aquino Ave',
    line: 'LRT-1',
    lineIndex: 23,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Ninoy Aquino Avenue', 'Exit 2 - Dr. Santos Avenue'],
    nearbyStreets: ['Ninoy Aquino Avenue', 'Dr. Santos Avenue'],
    nearbyPlaces: [
      { name: 'Ayala Malls Manila Bay', type: 'mall', distance: '1km' },
    ],
    latitude: 14.4865,
    longitude: 120.9892,
    status: 'Normal',
  },
  {
    id: 'lrt1-dr-santos',
    name: 'Dr. Santos',
    line: 'LRT-1',
    lineIndex: 24,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Dr. Santos Avenue', 'Exit 2 - Felix Y. Manalo Street'],
    nearbyStreets: ['Dr. Santos Avenue', 'Felix Y. Manalo Street'],
    nearbyPlaces: [
      { name: 'SM BF Parañaque', type: 'mall', distance: '1km' },
      { name: 'Las Piñas City Hall', type: 'landmark', distance: '2km' },
    ],
    latitude: 14.4714,
    longitude: 120.9849,
    status: 'Normal',
  },
];

export const LRT2_STATIONS: Station[] = [
  {
    id: 'lrt2-recto',
    name: 'Recto',
    line: 'LRT-2',
    lineIndex: 0,
    isTransfer: true,
    transferTo: ['LRT-1'],
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - C.M. Recto Avenue', 'Exit 2 - LRT-1 Connection'],
    nearbyStreets: ['C.M. Recto Avenue', 'Legarda Street'],
    nearbyPlaces: [
      { name: 'Isetann Recto', type: 'mall', distance: '100m' },
      { name: 'University Belt', type: 'school', distance: '200m' },
    ],
    latitude: 14.6033,
    longitude: 120.9836,
    status: 'Normal',
  },
  {
    id: 'lrt2-legarda',
    name: 'Legarda',
    line: 'LRT-2',
    lineIndex: 1,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Legarda Street'],
    nearbyStreets: ['Legarda Street', 'Mendiola Street'],
    nearbyPlaces: [
      { name: 'San Beda University', type: 'school', distance: '300m' },
    ],
    latitude: 14.6014,
    longitude: 120.9928,
    status: 'Normal',
  },
  {
    id: 'lrt2-pureza',
    name: 'Pureza',
    line: 'LRT-2',
    lineIndex: 2,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Pureza Street'],
    nearbyStreets: ['Pureza Street', 'V. Mapa Street'],
    nearbyPlaces: [],
    latitude: 14.6019,
    longitude: 121.0017,
    status: 'Normal',
  },
  {
    id: 'lrt2-v-mapa',
    name: 'V. Mapa',
    line: 'LRT-2',
    lineIndex: 3,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - V. Mapa Street'],
    nearbyStreets: ['V. Mapa Street', 'Old Sta. Mesa Street'],
    nearbyPlaces: [],
    latitude: 14.6040,
    longitude: 121.0095,
    status: 'Normal',
  },
  {
    id: 'lrt2-j-ruiz',
    name: 'J. Ruiz',
    line: 'LRT-2',
    lineIndex: 4,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - J. Ruiz Street'],
    nearbyStreets: ['J. Ruiz Street', 'N. Domingo Street'],
    nearbyPlaces: [],
    latitude: 14.6108,
    longitude: 121.0264,
    status: 'Normal',
  },
  {
    id: 'lrt2-gilmore',
    name: 'Gilmore',
    line: 'LRT-2',
    lineIndex: 5,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Gilmore Avenue'],
    nearbyStreets: ['Gilmore Avenue', 'Aurora Boulevard'],
    nearbyPlaces: [
      { name: 'Gilmore IT Center', type: 'shop', distance: '100m' },
    ],
    latitude: 14.6134,
    longitude: 121.0340,
    status: 'Normal',
  },
  {
    id: 'lrt2-betty-go-belmonte',
    name: 'Betty Go-Belmonte',
    line: 'LRT-2',
    lineIndex: 6,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Betty Go-Belmonte Street'],
    nearbyStreets: ['Betty Go-Belmonte Street', 'Aurora Boulevard'],
    nearbyPlaces: [],
    latitude: 14.6157,
    longitude: 121.0432,
    status: 'Normal',
  },
  {
    id: 'lrt2-araneta-cubao',
    name: 'Cubao',
    line: 'LRT-2',
    lineIndex: 7,
    isTransfer: true,
    transferTo: ['MRT-3'],
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Aurora Boulevard', 'Exit 2 - EDSA', 'Exit 3 - MRT-3 Connection'],
    nearbyStreets: ['Aurora Boulevard', 'EDSA'],
    nearbyPlaces: [
      { name: 'Gateway Mall', type: 'mall', distance: '100m' },
      { name: 'Ali Mall', type: 'mall', distance: '200m' },
      { name: 'Farmers Plaza', type: 'mall', distance: '150m' },
    ],
    latitude: 14.6225,
    longitude: 121.0530,
    status: 'Normal',
  },
  {
    id: 'lrt2-anonas',
    name: 'Anonas',
    line: 'LRT-2',
    lineIndex: 8,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Aurora Boulevard'],
    nearbyStreets: ['Aurora Boulevard', 'Anonas Street'],
    nearbyPlaces: [
      { name: 'Anonas LRT Mall', type: 'mall', distance: '50m' },
    ],
    latitude: 14.6280,
    longitude: 121.0650,
    status: 'Normal',
  },
  {
    id: 'lrt2-katipunan',
    name: 'Katipunan',
    line: 'LRT-2',
    lineIndex: 9,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Katipunan Avenue', 'Exit 2 - Aurora Boulevard'],
    nearbyStreets: ['Katipunan Avenue', 'Aurora Boulevard'],
    nearbyPlaces: [
      { name: 'Ateneo de Manila University', type: 'school', distance: '500m' },
      { name: 'UP Town Center', type: 'mall', distance: '1km' },
    ],
    latitude: 14.6310,
    longitude: 121.0730,
    status: 'Normal',
  },
  {
    id: 'lrt2-santolan',
    name: 'Santolan',
    line: 'LRT-2',
    lineIndex: 10,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Marcos Highway'],
    nearbyStreets: ['Marcos Highway', 'Imelda Avenue'],
    nearbyPlaces: [
      { name: 'SM Marikina', type: 'mall', distance: '1km' },
    ],
    latitude: 14.6221,
    longitude: 121.0863,
    status: 'Normal',
  },
  {
    id: 'lrt2-marikina',
    name: 'Marikina-Pasig',
    line: 'LRT-2',
    lineIndex: 11,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Marcos Highway'],
    nearbyStreets: ['Marcos Highway'],
    nearbyPlaces: [
      { name: 'Ayala Malls Marikina', type: 'mall', distance: '500m' },
    ],
    latitude: 14.6206,
    longitude: 121.1001,
    status: 'Normal',
  },
  {
    id: 'lrt2-antipolo',
    name: 'Antipolo',
    line: 'LRT-2',
    lineIndex: 12,
    isTransfer: false,
    firstTrain: '5:00 AM',
    lastTrain: '10:00 PM',
    platforms: 2,
    exits: ['Exit 1 - Marcos Highway', 'Exit 2 - Sumulong Highway'],
    nearbyStreets: ['Marcos Highway', 'Sumulong Highway'],
    nearbyPlaces: [
      { name: 'SM City Masinag', type: 'mall', distance: '1km' },
      { name: 'Antipolo Cathedral', type: 'landmark', distance: '3km' },
    ],
    latitude: 14.6246,
    longitude: 121.1213,
    status: 'Normal',
  },
];

export const ALL_STATIONS: Station[] = [...MRT3_STATIONS, ...LRT1_STATIONS, ...LRT2_STATIONS];

export function getStationById(id: string): Station | undefined {
  return ALL_STATIONS.find((s) => s.id === id);
}

export function getStationsByLine(line: LineId): Station[] {
  return ALL_STATIONS.filter((s) => s.line === line).sort((a, b) => a.lineIndex - b.lineIndex);
}

export function searchStations(query: string): Station[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return ALL_STATIONS.filter(
    (s) =>
      s.name.toLowerCase().includes(q) ||
      s.line.toLowerCase().includes(q) ||
      s.nearbyStreets.some((st) => st.toLowerCase().includes(q))
  );
}
