import React, { useRef, useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Linking,
  StatusBar,
  NativeSyntheticEvent,
  NativeScrollEvent,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import * as Haptics from 'expo-haptics';
import { LinearGradient } from 'expo-linear-gradient';

const LAST_UPDATED = 'January 2026';

interface Section {
  title: string;
  icon: keyof typeof Ionicons.glyphMap;
  color: string;
  content: string;
}

const SECTIONS: Section[] = [
  {
    title: 'Information We Collect',
    icon: 'document-text',
    color: '#1A73E8',
    content: `MetroRide PH is designed with a privacy-first approach. We collect only what is necessary to provide transit assistance.

Automatically Collected:
• App crash reports and diagnostic data (anonymized)
• App performance metrics to improve stability
• General usage patterns (screens visited, features used)

Optionally Provided:
• Approximate location (GPS) — only when you tap "Nearest Station." Never continuously tracked.
• Commuter profile preferences (stored locally, never uploaded)
• Community reports you submit voluntarily`,
  },
  {
    title: 'How We Use Your Data',
    icon: 'analytics',
    color: '#9C27B0',
    content: `Data collected is used exclusively for:

• Improving app performance and fixing bugs
• Providing accurate fare calculations and route suggestions
• Delivering location-based features (nearest station detection)
• Aggregating anonymous crowd reports for community features

We do NOT use your data for:
• Advertising or targeted marketing
• Building personal profiles or tracking
• Sharing with transit authorities or government agencies
• Any commercial purpose beyond improving the app`,
  },
  {
    title: 'Data Storage & Security',
    icon: 'shield-checkmark',
    color: '#34A853',
    content: `Local Storage (On Your Device):
• All user preferences, favorites, and settings are stored in AsyncStorage on your device
• Beep card information is stored locally only
• Community reports are cached locally and submitted anonymously

Cloud Storage (Supabase - Singapore):
• Anonymous transit data syncs (fare matrices, station updates)
• No personally identifiable information is stored in the cloud
• Connection is encrypted via HTTPS/TLS 1.3
• Supabase servers are located in ap-southeast-1 (Singapore)

Data is automatically deleted when you uninstall the app.`,
  },
  {
    title: 'App Permissions',
    icon: 'lock-closed',
    color: '#F59E0B',
    content: `MetroRide PH requests only minimal permissions:

INTERNET (Required)
• Used for: Fetching live fare updates, MetroAI responses, service alerts
• Cannot be used to: Access files, contacts, or any personal data

ACCESS_NETWORK_STATE (Required)
• Used for: Detecting offline mode to serve cached data
• Cannot be used to: Monitor network traffic or other apps

ACCESS_FINE_LOCATION (Optional)
• Used for: Finding the nearest MRT/LRT station to your location
• NOT used for: Continuous tracking, background location, or sharing location
• You can deny this permission without affecting core features`,
  },
  {
    title: 'AI Assistant (MetroAI)',
    icon: 'sparkles',
    color: '#8B5CF6',
    content: `MetroAI uses the Newell AI service (fastshot.ai) to process your queries.

What is sent to the AI:
• Your text messages and questions
• Optional: Images you manually upload for analysis
• Optional: Voice recordings you choose to transcribe

What is NOT sent:
• Your location or personal details
• Chat history is stored only on your device
• No persistent user ID is attached to AI requests

AI responses are generated by large language models and may not reflect real-time conditions. Always verify safety-critical information through official channels.`,
  },
  {
    title: 'Third-Party Services',
    icon: 'git-network',
    color: '#1143A8',
    content: `MetroRide PH integrates with the following services:

Supabase (supabase.com)
• Purpose: Transit data synchronization
• Data: Anonymous fare/station data only
• Privacy Policy: supabase.com/privacy

Newell AI / fastshot.ai
• Purpose: MetroAI assistant responses
• Data: Query text and optional images
• Privacy Policy: fastshot.ai/privacy

Expo / React Native
• Purpose: App framework and notifications
• Data: Anonymous crash reports
• Privacy Policy: expo.dev/privacy

Adapty (adapty.io)
• Purpose: Premium subscription management
• Data: Purchase transactions only
• Privacy Policy: adapty.io/privacy`,
  },
  {
    title: 'Your Rights',
    icon: 'person-circle',
    color: '#EA4335',
    content: `As a MetroRide PH user, you have the following rights:

Right to Access
• All your data is stored locally on your device and is fully accessible to you

Right to Delete
• Uninstalling the app deletes all locally stored data
• To request deletion of any server-side data: privacy@metrorideph.app

Right to Opt Out
• Location permission can be revoked at any time in device Settings
• Community reporting is always opt-in
• You can disable AI features by avoiding the MetroAI screen

Right to Portability
• Export your favorites and settings via the Settings screen (coming soon)

Contact for Privacy Concerns:
privacy@metrorideph.app`,
  },
  {
    title: 'Policy Updates',
    icon: 'refresh-circle',
    color: '#F5C500',
    content: `This Privacy Policy may be updated periodically to reflect:
• Changes in app features or data practices
• Updates to third-party service policies
• Legal or regulatory requirements

When we make significant changes:
• A prompt will be shown in-app for review
• The "Last Updated" date at the top will change
• For major changes, we may require fresh acceptance

Continued use of MetroRide PH after policy changes constitutes acceptance of the revised policy.

Last Updated: ${LAST_UPDATED}
Policy Version: 1.0`,
  },
];

export default function PrivacyPolicyScreen() {
  const insets = useSafeAreaInsets();
  const router = useRouter();
  const scrollRef = useRef<ScrollView>(null);
  const [scrollProgress, setScrollProgress] = useState(0);

  const handleScroll = (e: NativeSyntheticEvent<NativeScrollEvent>) => {
    const { contentOffset, contentSize, layoutMeasurement } = e.nativeEvent;
    const progress = (contentOffset.y + layoutMeasurement.height) / contentSize.height;
    setScrollProgress(Math.min(progress, 1));
  };

  return (
    <View style={styles.root}>
      <StatusBar barStyle="light-content" backgroundColor="#0A0F1E" />

      {/* Header */}
      <LinearGradient
        colors={['#0D1B3E', '#0A0F1E']}
        style={[styles.header, { paddingTop: insets.top + 8 }]}
      >
        <TouchableOpacity
          style={styles.backBtn}
          onPress={() => { Haptics.selectionAsync(); router.back(); }}
        >
          <Ionicons name="chevron-back" size={24} color="#fff" />
        </TouchableOpacity>
        <View style={styles.headerCenter}>
          <Text style={styles.headerTitle}>Privacy Policy</Text>
          <Text style={styles.headerSub}>Last updated: {LAST_UPDATED}</Text>
        </View>
        <TouchableOpacity
          style={styles.shareBtn}
          onPress={() => Linking.openURL('https://metrorideph.app/privacy')}
        >
          <Ionicons name="open-outline" size={20} color="rgba(255,255,255,0.6)" />
        </TouchableOpacity>
      </LinearGradient>

      {/* Progress bar */}
      <View style={styles.progressBar}>
        <View style={[styles.progressFill, { width: `${scrollProgress * 100}%` }]} />
      </View>

      <ScrollView
        ref={scrollRef}
        style={styles.scroll}
        contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + 32 }]}
        showsVerticalScrollIndicator={false}
        onScroll={handleScroll}
        scrollEventThrottle={50}
      >
        {/* Intro */}
        <View style={styles.introCard}>
          <View style={styles.introIcon}>
            <Ionicons name="shield-checkmark" size={28} color="#34A853" />
          </View>
          <Text style={styles.introTitle}>Your Privacy Matters</Text>
          <Text style={styles.introText}>
            MetroRide PH is committed to protecting your privacy. We built this app with a privacy-first approach — collecting the minimum data required to serve you as a Metro Manila commuter.
          </Text>
        </View>

        {/* Sections */}
        {SECTIONS.map((section, idx) => (
          <View key={section.title} style={styles.section}>
            <View style={styles.sectionHeader}>
              <View style={[styles.sectionIcon, { backgroundColor: `${section.color}18`, borderColor: `${section.color}30` }]}>
                <Ionicons name={section.icon} size={18} color={section.color} />
              </View>
              <Text style={styles.sectionTitle}>{section.title}</Text>
              <Text style={styles.sectionNum}>{String(idx + 1).padStart(2, '0')}</Text>
            </View>
            <Text style={styles.sectionBody}>{section.content}</Text>
          </View>
        ))}

        {/* Contact */}
        <View style={styles.contactCard}>
          <Ionicons name="mail" size={22} color="#1A73E8" />
          <View style={styles.contactContent}>
            <Text style={styles.contactTitle}>Questions or Concerns?</Text>
            <Text style={styles.contactSub}>We respond within 48 hours</Text>
          </View>
          <TouchableOpacity
            style={styles.contactBtn}
            onPress={() => Linking.openURL('mailto:privacy@metrorideph.app')}
          >
            <Text style={styles.contactBtnText}>Contact</Text>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#0A0F1E' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 12,
    gap: 8,
  },
  backBtn: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.08)',
    flexShrink: 0,
  },
  headerCenter: { flex: 1, paddingHorizontal: 8 },
  headerTitle: { fontSize: 17, fontWeight: '700', color: '#fff' },
  headerSub: { fontSize: 11, color: 'rgba(255,255,255,0.4)', marginTop: 2 },
  shareBtn: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.06)',
    flexShrink: 0,
  },
  progressBar: { height: 2, backgroundColor: 'rgba(255,255,255,0.06)' },
  progressFill: { height: '100%', backgroundColor: '#1A73E8', borderRadius: 1 },

  scroll: { flex: 1 },
  content: { paddingHorizontal: 16, paddingTop: 16 },

  introCard: {
    backgroundColor: 'rgba(52,168,83,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(52,168,83,0.2)',
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    marginBottom: 16,
  },
  introIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(52,168,83,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  introTitle: { fontSize: 18, fontWeight: '700', color: '#fff', marginBottom: 8 },
  introText: { fontSize: 13, color: 'rgba(255,255,255,0.65)', textAlign: 'center', lineHeight: 20 },

  section: {
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
    padding: 16,
    marginBottom: 10,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  sectionIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    flexShrink: 0,
  },
  sectionTitle: { flex: 1, fontSize: 15, fontWeight: '700', color: '#fff' },
  sectionNum: { fontSize: 11, color: 'rgba(255,255,255,0.2)', fontWeight: '600' },
  sectionBody: { fontSize: 13, color: 'rgba(255,255,255,0.65)', lineHeight: 21 },

  contactCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'rgba(26,115,232,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(26,115,232,0.2)',
    borderRadius: 14,
    padding: 16,
    marginTop: 8,
  },
  contactContent: { flex: 1 },
  contactTitle: { fontSize: 14, fontWeight: '600', color: '#fff' },
  contactSub: { fontSize: 12, color: 'rgba(255,255,255,0.45)', marginTop: 2 },
  contactBtn: {
    backgroundColor: '#1A73E8',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  contactBtnText: { fontSize: 13, fontWeight: '700', color: '#fff' },
});
